movieapp/urls.py
from . import views
from django.urls import path, include
app_name='movie_app'
urlpatterns = [

    path('',views.index, name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movieproject/urls.py
from django.contrib import admin
from django.urls import path, include

from movieproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie': movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()


    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieapp/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br>
    <input type="text" name="desc" placeholder="Enter movie description"><br>
    <input type="number" name="year" placeholder="Enter movie releasing year"><br>
    <input type="file" name="img" ><br>
    <input type="submit">


</form>
{% endblock %}

movieapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online movie store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieapp/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete this movie?
    <input type="submit">
</form>

movieapp/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col_md_6">
            <img src="{{movie.img.url}}" width="300" height="400">

        </div>
        <div class="col-md-6">
            <h4>{{movie.name}}</h4>
            <h6>{{movie.desc}}</h6>
            <h6>{{movie.year}}</h6>
            <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a>

        </div>
    </div>
</div>



{% endblock %}

movieapp/templates/edit.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}

</form>

movieapp/templates/index.html
{% extends 'base.html' %}
{% block body %}

<h1><u>Movies list</u></h1>
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 15rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100" height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url  'movie_app:detail' i.id %}" class="btn btn-primary">Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>





{% endblock %}